### ISSUE TITLE
可以在整理字幕的时候，让一个意群的字幕尽量出现在一起吗？

### ISSUE THREAD

**Issue by iwanttobepowerful** [mayf09/6.S081-2020-video-subtitles#3]
你好，可以在整理字幕的时候，让一个意群的字幕尽量出现在一起吗，太分散的话不太容易前后联系起来。多谢啦！

**Comment by mayf09** [comment]
> 你好，可以在整理字幕的时候，让一个意群的字幕尽量出现在一起吗，太分散的话不太容易前后联系起来。多谢啦！

有道理。
只是为了加快进度，对于长句，是用脚本按照标点符号断句的。
把主要时间放在了翻译上面，后面还会再对字幕进行校对。

**Comment by iwanttobepowerful** [comment]
@mayf09 Lec3我在你的基础上整理了30分钟了

**Comment by mayf09** [comment]
> @mayf09 Lec3我在你的基础上整理了30分钟了

好的，改了哪些地方？

**Comment by iwanttobepowerful** [comment]
@mayf09 非常多

**Comment by mayf09** [comment]
使用了新的脚本工具， https://github.com/mayf09/subtitle-tools ，支持校正同时断句。
具体效果可以查看 Lecture 5 。

**Comment by iwanttobepowerful** [comment]
nice
